# Prezto Initialization
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Import alias
source "${ZDOTDIR:-$HOME}/.dotfiles/zsh/alias/entrypoint"

# Import exports
source "${ZDOTDIR:-$HOME}/.dotfiles/zsh/exports/entrypoint"

# Import functions
source "${ZDOTDIR:-$HOME}/.dotfiles/zsh/functions/entrypoint"
